message-delay: 8 #seconds
dialogue:
  - "<green>Hey there! I'm Clive."
  - "<green>Welcome to <b><gradient:#00AA00:#FFAA00>WorldMC</gradient></b>. <dark_aqua>It's earth in Minecraft!</dark_aqua>"
  - "<green>And, just like the real thing, its got <red>war, economy, towns, and people!</red> You'll have a lot to do!"
  - "<green>Let me tell you how things are done around here.<newline><light_purple>Pay attention now."
  - "<green>We use the towny plugin. Basic commands include:<newline><aqua>/town create, claim, invite, join, leave<newline><green><italic>You''ll figure it out as you go, trust me."
  - "<green>Rules are pretty chill:<newline><dark_aqua>
    • Don't be a jerk with town names<newline>
    • No discrimination (we're better than that)<newline>
    • Keep it PG-13ish (you know what I mean)"
  - "<green>Check us out:<newline><gold><click:open_url:https://worldmc.net>➤ Website</click>\n<blue><click:open_url:https://discord.gg/wmc>➤ Discord</click>"
  - "<green>Good luck out there! <yellow><bold>#saveClive"